---
# tasks file for webserver

- name: install nginx
  yum:
    name: "nginx"
    state: present

- name: ensure nginx is started
  service:
      name: nginx
      state: started

- name: permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: https
    permanent: yes
    state: enabled

- name: permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled