---
- name: webserver
  hosts: _frontendserver
  become: yes
  become_method: sudo
  gather_facts: true
  
  vars:
    picture_width: 500
    picture_height: 500
  
  pre_tasks:
    - name:  Wait for system to become reachable...
      wait_for_connection:
        timeout: 30
  
  roles:
    - role: webserver
    - role: website

  post_tasks:
    - name: Flag system as provisioned by ansible
      shell: echo "$(date --iso-8601=seconds)" > /etc/last_ansible_run
